name: Backend Build

on:
  push:
    branches:
      - main

jobs:
  checkout-and-print-tree:
      runs-on: ubuntu-24.04 [Beta]
      steps:
        - name: Check out repository code
          uses: actions/checkout@v3
        - name: Print project tree
          run: tree .